- name: Install devel tools
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  become: true
  with_items:
    - gcc
    - git
    - python
    - python-pip
    - ruby
    - rubygems-integration
    - rake
    - avr-libc
    - avrdude
    - gcc-avr
    - g++
