- name: Install comms packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - thunderbird
    - chromium-browser
    - firefox
    - pidgin
    - minicom
    - picocom
