- name: Install other utils
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  become: true
  with_items:
    - kupfer
    - ansible
    - apt-file
    - cryptsetup
    - expect
    - galculator
    - id3ren
    - id3v2
    - mplayer
    - pulseaudio-module-bluetooth
    - sox
    - sshpass
    - sqlite3
    - vlc
    - vorbis-tools
    - xfce4-clipman
