- name: Push files from ansible runner host home directory to target machine home directory
  copy:
    src: "~/{{ item }}/"
    dest: "~/{{ item }}"
  with_items:
    - bin
    - .config/galculator
    - .config/autostart
    - .config/kupfer
    - .config/xfce4
    - .config/Thunar
    - .config/gtk-3.0
    - .config/ranger
