- name: Create my user
  become: yes
  user:
    name: "{{ deployuser }}"
    shell: "/bin/bash"
    uid: 1000
    createhome: yes

- name: Set up authorized keys for the deployer user
  authorized_key:
    user: "{{ deployuser }}"
    key: "{{ item }}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: Make sure we have a 'wheel' group
  become: yes
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Add user to wheel group
  become: yes
  user: name={{ deployuser }} groups=wheel append=yes state=present createhome=yes
  ignore_errors: yes # TODO: upon deployment remove this line 
